### PR TITLE
test the openapi

### PR DESCRIPTION
**Pull request by erog-tech**

### CODE REVIEW

**Comment by erog-tech** [comment]
@tlcoles I have tested the openweather api and added the changes in the code, have a look and approve it accordingly.

**Review by tlcoles — CHANGES_REQUESTED** [review]
you have a config file in your .gitignore that is called on line 3 in the index, so the index no longer works. and I believe the settings.json file is also not for this project but for your computer. please fix those issues.

**Review by tlcoles — COMMENTED** [review]
It looks like you wanted to Add gitignore file to hide the API keys. What's the reason that you want to do that at this stage?

**Comment by erog-tech** [comment]
@tlcoles  API keys should not be visible to public, and should never be deployed in plain text, therefore I created a .gitignore file to ignore the config.js file,  you have to create config.js file and add the API key there. After that index.html will work

**Review by tlcoles — APPROVED** [review]

**Pull request merged**
